name: ci-cd

on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm test

  deploy:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Construir imagen Docker
        run: docker build -t app-ejemplo-evaluacion:${{ github.sha }} .
      - name: Validar despliegue condicionado
        run: echo "Pruebas aprobadas exitosamente. El despliegue condicionado se ha ejecutado correctamente."